In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

%matplotlib inline

In [3]:
df = pd.read_csv("WineQuality.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0

In [4]:
df_columns = df.columns.tolist()
df_columns

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1699 entries, 0 to 1698
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1699 non-null   float64
 1   volatile acidity      1699 non-null   float64
 2   citric acid           1699 non-null   float64
 3   residual sugar        1699 non-null   float64
 4   chlorides             1699 non-null   float64
 5   free sulfur dioxide   1699 non-null   float64
 6   total sulfur dioxide  1699 non-null   float64
 7   density               1699 non-null   float64
 8   pH                    1699 non-null   float64
 9   sulphates             1699 non-null   float64
 10  alcohol               1699 non-null   float64
 11  quality               1699 non-null   float64
dtypes: float64(12)
memory usage: 159.4 KB

In [6]:
def plot(data,cols):
    plot  = px.histogram(data,y =cols,x = data["quality"],title=f"Quality vs {cols}")
    plot.show()

In [7]:
for i in df_columns:
    plot(df,i)

In [8]:
inputs = df.drop("quality",axis=1)
target = df["quality"]
inputs

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.400000,0.700000,0.000000,1.900000,0.076000,11.000000,34.000000,0.997800,3.510000,0.560000,9.400000
1,7.800000,0.880000,0.000000,2.600000,0.098000,25.000000,67.000000,0.996800,3.200000,0.680000,9.800000
2,7.800000,0.760000,0.040000,2.300000,0.092000,15.000000,54.000000,0.997000,3.260000,0.650000,9.800000
3,11.200000,0.280000,0.560000,1.900000,0.075000,17.000000,60.000000,0.998000,3.160000,0.580000,9.800000
4,7.400000,0.700000,0.000000,1.900000,0.076000,11.000000,34.000000,0.997800,3.510000,0.560000,9.400000
...,...,...,...,...,...,...,...,...,...,...,...
1694,7.801551,0.774154,0.241745,2.715859,0.079321,16.037881,10.405468,0.994029,3.557283,0.514583,9.366488
1695,7.207143,0.290908,0.590842,3.962575,0.055079,39.435754,78.763287,0.996134,2.925239,1.046480,8.942161
1696,10.100031,0.964682,0.540634,3.333877,0.115459,24.801783,71.432995,0.997277,3.327200,0.647539,9.619507
1697,5.372036,0.510212,0.078397,0.982824,0.095933,30.435484,76.676115,0.993783,3.158328,0.817616,9.375978
1698,9.277331,0.354429,0.291503,0.900000,0.059163,19.219891,6.000000,0.997578,3.308081,0.751800,10.661601

In [9]:
from sklearn.model_selection import train_test_split
train_input ,test_input,train_target,test_target = train_test_split(inputs,target,test_size=0.3,random_state=42)
train_input

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
846,6.400000,0.640000,0.210000,1.800000,0.081000,14.000000,31.000000,0.996890,3.590000,0.660000,9.800000
1361,8.300000,0.850000,0.140000,2.500000,0.093000,13.000000,54.000000,0.997240,3.360000,0.540000,10.100000
1609,9.696900,0.364986,0.544242,0.900000,0.115087,38.787432,13.883779,0.995678,3.326498,0.572806,8.770491
177,7.500000,0.520000,0.420000,2.300000,0.087000,8.000000,38.000000,0.997200,3.580000,0.610000,10.500000
1654,7.320836,0.429900,0.264595,1.772616,0.053916,16.988199,38.080234,0.999585,2.901839,0.843167,11.750896
...,...,...,...,...,...,...,...,...,...,...,...
1130,9.100000,0.600000,0.000000,1.900000,0.058000,5.000000,10.000000,0.997700,3.180000,0.630000,10.400000
1294,8.200000,0.635000,0.100000,2.100000,0.073000,25.000000,60.000000,0.996380,3.290000,0.750000,10.900000
860,7.200000,0.620000,0.060000,2.700000,0.077000,15.000000,85.000000,0.997460,3.510000,0.540000,9.500000
1459,7.900000,0.200000,0.350000,1.700000,0.054000,7.000000,15.000000,0.994580,3.320000,0.800000,11.900000
1126,5.800000,0.290000,0.260000,1.700000,0.063000,3.000000,11.000000,0.991500,3.390000,0.540000,13.500000

In [10]:
input_cols = list(train_input.columns)
input_cols

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol']

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(inputs)

MinMaxScaler()

In [12]:
train_input_array = scaler.transform(train_input)
test_input_array = scaler.transform(test_input)
train_input_scaled = pd.DataFrame(
    train_input_array,
    columns=train_input.columns,
    index= train_input.index
)
test_input_scaled = pd.DataFrame(
    test_input_array,
    columns=test_input.columns,
    index= test_input.index
)
train_input_scaled

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
846,0.159292,0.356164,0.210000,0.061644,0.115192,0.183099,0.088339,0.500734,0.669291,0.197605,0.215385
1361,0.327434,0.500000,0.140000,0.109589,0.135225,0.169014,0.169611,0.526432,0.488189,0.125749,0.261538
1609,0.451053,0.167799,0.544242,0.000000,0.172099,0.532217,0.027858,0.411739,0.461809,0.145393,0.056999
177,0.256637,0.273973,0.420000,0.095890,0.125209,0.098592,0.113074,0.523495,0.661417,0.167665,0.323077
1654,0.240782,0.212260,0.264595,0.059768,0.069977,0.225186,0.113358,0.698621,0.127433,0.307286,0.515522
...,...,...,...,...,...,...,...,...,...,...,...
1130,0.398230,0.328767,0.000000,0.068493,0.076795,0.056338,0.014134,0.560206,0.346457,0.179641,0.307692
1294,0.318584,0.352740,0.100000,0.082192,0.101836,0.338028,0.190813,0.463289,0.433071,0.251497,0.384615
860,0.230088,0.342466,0.060000,0.123288,0.108514,0.197183,0.279152,0.542584,0.606299,0.125749,0.169231
1459,0.292035,0.054795,0.350000,0.054795,0.070117,0.084507,0.031802,0.331131,0.456693,0.281437,0.538462
1126,0.106195,0.116438,0.260000,0.054795,0.085142,0.028169,0.017668,0.104993,0.511811,0.125749,0.784615

In [13]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train_input_scaled,train_target)

LinearRegression()

In [14]:
model.coef_

array([ 0.45658009, -1.5964406 , -0.1470371 ,  0.23265735, -1.14335619,
        0.34025166, -0.8169141 , -0.48290735, -0.26410129,  1.24673637,
        1.7301218 ])

In [15]:
pred = model.predict(test_input)
pred

array([ 1.54101808e+01, -1.88418052e+01, -2.10375797e+01,  7.52172831e+00,
        9.51630692e+00, -4.67902972e+01,  1.68853131e+01,  1.25422167e+00,
       -3.15528140e+01,  7.18453143e+00, -2.27422631e+01,  1.76397662e+01,
       -1.76934877e+01,  1.74175491e+01,  1.60946558e+01,  1.38411965e+01,
       -3.72458427e+01,  1.52291244e+01, -1.33993966e+01,  5.81571995e+00,
        7.01112747e+00, -2.68367651e+01,  1.78009816e+01, -3.66027269e+01,
        3.41121459e-01, -3.24944718e+01, -2.16776595e+01,  8.60188184e+00,
        2.42584722e+01, -1.53160417e+01, -3.17733894e+01, -6.08186467e+01,
       -1.12164574e+01, -2.72977999e+01, -1.45377996e+01,  9.74828721e+00,
        1.85677143e+01,  1.41055019e+01,  1.64845707e+01, -6.66934895e+00,
       -5.11817986e+01,  1.91579393e+01,  1.63124239e+00,  1.41990503e+01,
       -9.95856744e+00,  3.16904607e+00,  2.11288474e+01,  7.01112747e+00,
        1.69756634e+01,  1.37726841e+01,  7.35895094e+00,  1.97575383e+01,
       -5.11020564e+01,  2.61517703e+00,  1.97651980e+00,  1.31943159e+01,
       -8.70827610e+01, -5.91374841e+01,  2.67478066e+00,  1.10718612e+00,
        2.46890635e+00,  7.93354506e+00,  2.08355902e+01, -1.33993966e+01,
        1.25184203e+01,  8.18730098e+00, -1.47449677e+00, -1.12932647e+01,
       -2.57318456e+01,  1.03550665e+01, -5.36175343e+01,  1.72286018e+01,
        1.29191043e+01,  1.91512741e+01,  1.55113266e+01, -2.10602431e+01,
       -2.34814094e+01,  1.59148733e+01,  2.44826152e+00,  5.00642482e+00,
       -9.02377451e+00,  1.45787966e+01,  1.35573368e+01,  5.60518874e+00,
        1.73978762e+01, -7.05610915e+00, -3.15080574e+01, -3.62857213e+01,
       -1.94210066e+01, -3.55496365e-01,  5.48768516e-01,  1.35450140e+01,
       -5.03715650e+00, -1.98624381e+00,  1.51909579e+01, -4.00970157e+01,
        2.74965764e+00,  5.37010173e+00, -2.15317667e+01, -4.08652585e+00,
        3.69067281e+00, -6.65122263e+00,  1.51426081e+01, -3.49601318e+01,
       -6.62700649e+01, -3.46896789e+01, -2.96222761e+01, -1.76326302e+00,
       -2.82948535e+00,  4.86362588e+00,  1.38478016e+01,  1.53157793e+00,
       -6.18741386e+01,  2.25438382e+01,  2.02400402e+01,  8.88579706e+00,
        6.29612706e+00,  2.58565533e+01,  1.57363042e+01,  7.72502409e+00,
       -9.53912581e-01,  2.43904720e+01, -2.49805863e+00, -4.64309282e+00,
       -2.03106611e+01,  2.59720287e+00,  1.65006146e+01,  1.09284573e+01,
        1.69826736e+01, -2.43072861e+01,  1.24700967e+01, -1.01151563e+01,
       -2.72289914e+00, -2.13974747e-01, -2.54505485e+01,  2.20857408e+01,
        9.06100017e+00,  8.01534467e+00, -4.94096070e+00, -2.48190170e+00,
       -1.32877967e+01,  2.13252887e+01, -8.46699702e+01,  6.45308544e+00,
       -1.22916652e+01,  1.60328348e+01,  1.88745653e+01, -3.75493231e+01,
       -4.58213262e+01,  1.13139156e+01, -3.57993775e+01, -1.47545512e+01,
       -5.08733800e+00,  8.27112482e+00,  2.18503465e+01, -5.17977456e+01,
       -3.02069993e+01,  1.31943159e+01, -7.83324169e-01,  1.31200021e+01,
       -4.21533685e+01,  5.57339848e+00,  5.82394940e+00, -3.66348105e+01,
        1.94706149e+00,  1.77006216e+01,  2.08294374e+01, -4.63432947e+01,
        1.00363235e+01,  1.50501151e+01,  1.21388901e+01,  1.50693129e+01,
        2.04856348e+01,  1.04067426e+01,  1.24741208e+01, -3.09431300e-01,
       -6.73674146e+00,  1.29861779e+00, -5.80498894e+00, -7.38895269e+00,
       -8.83755903e+01, -9.01808071e+00, -4.98820758e+01, -2.07967484e+01,
       -1.43038426e+01,  3.20466207e+00,  7.17224006e+00, -2.45126136e+01,
       -7.89529791e+01,  1.44558083e+01, -4.50200269e+01, -4.29408580e+00,
       -1.03837691e+01,  1.01086392e+01,  1.66019340e+01, -3.16458635e+01,
        1.38903308e+01, -3.19089877e+00, -8.55209277e-01,  6.76185178e-02,
        4.14259914e-01, -3.66869116e+01, -1.30303515e+01,  1.81237895e+00,
        1.83021316e+01, -8.37327113e+00,  2.32720379e+01, -3.09002746e+01,
        1.27870448e+01, -5.28706215e+00,  3.40417933e+00,  2.12229709e+01,
       -5.55065569e+00,  9.21679974e+00,  8.75739955e-02, -3.67093379e+01,
       -2.45658324e+01, -5.87199783e+00,  1.20493738e+01,  1.27351842e+01,
        1.55039222e+01,  1.30769811e+01,  1.97575383e+01, -1.43648611e+01,
        2.04263128e+01, -1.95768733e+01,  1.22867076e+01, -4.37679128e+01,
       -2.06089664e+01,  1.52073912e+01,  1.07852636e+01, -4.74183351e+01,
        9.09001478e+00,  1.70542228e+01, -3.51735274e+01,  1.27392433e+01,
        4.37496113e+00, -3.89808370e+01, -7.50240307e+00, -2.44270849e+01,
       -2.06975358e+01, -9.22423068e+00, -1.45365433e+01, -2.39746253e+01,
       -2.11676352e+01,  2.43857514e+01,  9.06864504e+00, -5.80223074e+00,
        1.08634867e+00, -1.48360218e+01,  2.80735098e+00, -4.37620264e+01,
       -2.87313005e+01,  4.16132157e-01,  2.71396648e+00,  1.23949545e+01,
        9.39592258e+00,  2.52230800e+00,  5.29330833e+00,  1.83359086e+01,
        1.99575132e+01, -1.97822414e+01, -3.28488002e+00, -1.43888380e+01,
        1.32573822e+01,  1.92908411e+01,  8.54750104e+00, -3.50492097e+00,
        1.20372142e+00,  1.78617720e+01,  9.04143727e+00,  1.14724340e+01,
        1.92498257e+01, -3.29350724e+01, -3.59189800e+01, -9.47134834e+00,
       -1.77997490e+01,  1.56805348e+01,  1.62481070e+01,  1.58298550e+01,
        1.99762856e+01,  8.43749043e+00, -9.21562287e+00,  1.70015622e+01,
        1.49495489e+01,  4.36528982e+00, -6.39325955e+00,  4.74608255e+00,
        2.38645648e+01,  1.56563694e+01, -4.23658815e+01, -7.83271821e+01,
        2.20317836e+01,  1.43399619e+01,  1.52766999e+01, -2.87816811e+01,
       -7.94091266e+00,  3.37812954e+00, -6.87281418e+01,  7.72035197e+00,
       -8.99764274e+00,  5.13836406e+00, -8.66812919e+01, -1.88049941e+01,
       -3.62323136e-01,  1.76516332e+01, -4.15859667e+01,  1.02927743e+00,
       -1.22955805e+01,  6.44848902e+00, -1.30391081e+01,  4.91531616e+00,
        1.96231969e+01, -6.13166812e+01,  2.99759122e+00,  1.09892289e+01,
       -1.12031795e+01, -4.21596825e+01, -6.69990735e+01,  1.08688220e+01,
        1.53475779e+00, -2.37172223e+01, -4.99657121e+01, -1.28450245e+01,
       -1.05240513e+01,  1.58008715e+01,  1.63436585e+01, -2.16776595e+01,
       -1.54086656e+01,  6.27568613e+00, -6.02608392e+00,  1.46180790e+01,
        6.90378511e+00, -5.64330336e+01,  1.88324962e+00, -1.20714763e+01,
       -3.05001014e+01,  1.54976496e+01,  3.30931903e+00, -1.09833566e+01,
       -9.32673476e+00, -1.83059063e+01, -1.47449677e+00, -4.87442254e+01,
        1.51041550e+01,  1.73604618e+01,  8.42756588e+00,  1.58789907e+01,
       -7.30120092e+01,  6.80131869e+00, -1.48757264e+01,  1.30582940e+01,
       -5.58702252e-01,  7.27904399e+00, -3.09884417e+01, -1.04663156e+01,
        1.09886344e+01,  4.42469480e-02, -1.19075322e+01, -6.13873062e+01,
        2.00533216e+01, -3.01687765e+00, -1.58914716e+01,  5.07303109e+00,
        3.69379889e+00,  1.26157042e+01,  5.30317793e+00,  5.18438716e+00,
       -1.76302512e+01, -7.30786065e+01, -4.15303315e+01,  3.16159409e+00,
       -4.42637165e+00, -1.53055056e+01,  1.76471218e+01, -3.17201044e+01,
        1.50910000e+01,  1.56672143e+01,  1.57491934e+01,  1.39542443e+01,
        2.41483831e+00,  1.85595763e+01, -1.48232601e+01, -7.78581535e+00,
       -6.60095383e+00, -3.28736774e+00, -1.67926059e+01, -8.98136448e+00,
        1.94115806e+01, -7.43326233e+00,  2.56925795e+01,  1.16991889e+01,
       -1.94594601e+01,  1.63026725e+01, -2.67643289e+01,  1.82281489e+01,
       -1.62913533e+01,  1.62662039e+01,  1.53925352e+01, -3.78359238e+01,
        1.58982295e+01, -1.61516671e+01,  4.86362588e+00,  1.33640120e+01,
       -4.02763462e+01, -3.50822625e+00,  7.61041923e+00,  3.84674607e+00,
        2.09205313e+01,  1.29861779e+00, -2.84625370e+01,  2.27834761e+01,
       -4.90077645e+01,  1.86661496e+01,  1.13139156e+01, -4.37620264e+01,
        1.27870448e+01,  1.33053516e+01, -4.03491721e+01, -3.03631408e+00,
        2.91843507e+00,  1.35818798e+01,  1.38118338e+01, -5.82980824e+00,
       -3.51642566e+00, -1.45590783e+01, -4.66766716e+01,  1.54991006e+01,
       -3.07980356e+00,  1.27870448e+01, -1.29313914e+01,  1.43399619e+01,
        6.32975529e+00,  7.16988355e-01, -1.65518695e+01,  5.18438716e+00,
        1.82193943e+01, -6.34467580e+01, -9.26749760e+01,  2.71566571e+00,
       -2.86874703e-01, -6.18256775e+00,  4.53700741e+00, -6.66643324e+01,
        4.31476969e+00,  1.57588073e+01, -5.73421147e+00, -6.10683786e+01,
       -1.80163760e+01,  1.43921420e+01, -1.34890747e+01,  2.21120560e+01,
        2.09228114e+01, -6.06903017e-02, -1.30954481e+01,  1.35818798e+01,
       -1.42947871e+01,  7.26793684e+00, -3.82636984e+00,  1.04182728e+01,
       -2.23062768e+01,  3.04516367e+01,  1.70571853e+01, -3.89808370e+01,
       -1.21774760e+01,  7.01112747e+00, -5.90636607e+01,  1.98076175e+01,
       -7.88246911e+00, -8.67532267e+00,  1.60815560e+01,  8.62779444e+00,
        1.20635073e+01, -6.76516595e+01,  2.43170250e+01,  4.54296792e+00,
        7.14054543e+00, -1.34465453e+01,  1.09665037e+01, -4.46469453e+00,
       -6.51835012e+01,  3.88510865e+00,  6.41863330e+00,  6.11827185e+00,
       -8.96520747e+00,  3.05198590e+00, -7.03930917e+00,  1.44794012e+01,
       -1.44890516e+01,  1.48187605e+01, -3.04500964e+01,  4.36528982e+00,
        1.80020854e+00, -6.72128490e+01, -4.27759515e+01, -8.63362379e+01,
       -9.53912581e-01, -1.31197236e+00, -4.32263671e+00, -4.05199058e+01,
        2.34664856e+01,  2.12231067e+01,  2.59720287e+00, -1.09948446e+01,
        1.64123559e+01, -5.05886012e+00,  1.15783704e+01,  1.85026158e+01,
        2.14583755e+00, -3.10660874e+01])

In [16]:
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error
print(f"RMSE:{root_mean_squared_error(test_target,pred)}")
print(f"MAE:{mean_absolute_error(test_target,pred)}")
print(f"R2:{r2_score(test_target,pred)}")

RMSE:26.025801779163576
MAE:17.962249733902762
R2:-1091.9839153928776

In [17]:

data = pd.read_csv("WineQuality.csv")
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0

In [18]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1699 entries, 0 to 1698
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1699 non-null   float64
 1   volatile acidity      1699 non-null   float64
 2   citric acid           1699 non-null   float64
 3   residual sugar        1699 non-null   float64
 4   chlorides             1699 non-null   float64
 5   free sulfur dioxide   1699 non-null   float64
 6   total sulfur dioxide  1699 non-null   float64
 7   density               1699 non-null   float64
 8   pH                    1699 non-null   float64
 9   sulphates             1699 non-null   float64
 10  alcohol               1699 non-null   float64
 11  quality               1699 non-null   float64
dtypes: float64(12)
memory usage: 159.4 KB

In [19]:
x = data.drop(columns=["quality"])
y = data["quality"]
print(x)
print(y)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0          7.400000          0.700000     0.000000        1.900000   0.076000
1          7.800000          0.880000     0.000000        2.600000   0.098000
2          7.800000          0.760000     0.040000        2.300000   0.092000
3         11.200000          0.280000     0.560000        1.900000   0.075000
4          7.400000          0.700000     0.000000        1.900000   0.076000
...             ...               ...          ...             ...        ...
1694       7.801551          0.774154     0.241745        2.715859   0.079321
1695       7.207143          0.290908     0.590842        3.962575   0.055079
1696      10.100031          0.964682     0.540634        3.333877   0.115459
1697       5.372036          0.510212     0.078397        0.982824   0.095933
1698       9.277331          0.354429     0.291503        0.900000   0.059163

      free sulfur dioxide  total sulfur dioxide   density        pH  \
0               11.000000             34.000000  0.997800  3.510000
1               25.000000             67.000000  0.996800  3.200000
2               15.000000             54.000000  0.997000  3.260000
3               17.000000             60.000000  0.998000  3.160000
4               11.000000             34.000000  0.997800  3.510000
...                   ...                   ...       ...       ...
1694            16.037881             10.405468  0.994029  3.557283
1695            39.435754             78.763287  0.996134  2.925239
1696            24.801783             71.432995  0.997277  3.327200
1697            30.435484             76.676115  0.993783  3.158328
1698            19.219891              6.000000  0.997578  3.308081

      sulphates    alcohol
0      0.560000   9.400000
1      0.680000   9.800000
2      0.650000   9.800000
3      0.580000   9.800000
4      0.560000   9.400000
...         ...        ...
1694   0.514583   9.366488
1695   1.046480   8.942161
1696   0.647539   9.619507
1697   0.817616   9.375978
1698   0.751800  10.661601

[1699 rows x 11 columns]
0       5.000000
1       5.000000
2       5.000000
3       6.000000
4       5.000000
          ...
1694    3.897010
1695    4.307249
1696    5.409358
1697    5.454616
1698    6.737661
Name: quality, Length: 1699, dtype: float64

In [20]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1359, 11)
(340, 11)
(1359,)
(340,)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_final = scaler.fit_transform(x_train)
x_test_final = scaler.transform(x_test)
print(x_test_final)

[[ 1.76470536 -0.87703144  0.72850444 ... -1.46256306  0.84135346
  -1.04667099]
 [ 0.64920394 -0.70838046  0.21270281 ... -1.5938687  -0.15508687
   0.07608929]
 [ 0.06209793  1.23110585 -0.81890044 ... -0.80603485  0.95858174
  -0.76598092]
 ...
 [ 1.35373115 -0.25864451  1.91484818 ... -0.34646511  0.02075554
   1.19884957]
 [-0.99469288  0.30352544 -1.2831219  ...  0.44136874  0.02075554
   2.04091978]
 [ 0.12080853 -0.37107849  0.21270281 ...  0.11310464 -0.6826141
  -0.57885421]]

In [22]:
from sklearn.linear_model import (
    LinearRegression,Ridge,Lasso,ElasticNet,
    BayesianRidge,ARDRegression,SGDRegressor,
    PassiveAggressiveRegressor,HuberRegressor,
    RANSACRegressor,TheilSenRegressor
)
from sklearn.metrics import r2_score,root_mean_squared_error

models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "ElasticNet": ElasticNet(),
    "BayesianRidge": BayesianRidge(),
    "ARDRegression": ARDRegression(),
    "SGDRegressor": SGDRegressor(max_iter=1000),
    "PassiveAggressive": PassiveAggressiveRegressor(max_iter=1000),
    "Huber": HuberRegressor(),
    "RANSAC": RANSACRegressor(),
    "TheilSen": TheilSenRegressor()
}

results = []

for name,model in models.items():
    
    try:
        model.fit(x_train_final,y_train)
        y_pred = model.predict(x_test_final)
    
        r2 = r2_score(y_test,y_pred)
        rmse = root_mean_squared_error(y_test,y_pred)
    
        results.append((name,r2,rmse))
    except Exception as e:
        print(f"{name} failed :{e}")

results_df = pd.DataFrame(results,columns=["Model","r2-score","RMSE"])
results_df = results_df.sort_values(by="RMSE",ascending=False)

results_df

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\deprecation.py:71: FutureWarning: Class PassiveAggressiveRegressor is deprecated; this is deprecated in version 1.8 and will be removed in 1.10. Use `SGDRegressor(loss='epsilon_insensitive', penalty=None, learning_rate='pa1', eta0 = 1.0)` instead.
  warnings.warn(msg, category=FutureWarning)

                Model  r2-score      RMSE
7   PassiveAggressive -0.277701  0.879646
3          ElasticNet -0.000773  0.778504
2               Lasso -0.000773  0.778504
9              RANSAC  0.111491  0.733541
6        SGDRegressor  0.264649  0.667330
10           TheilSen  0.268561  0.665552
5       ARDRegression  0.271268  0.664320
8               Huber  0.271788  0.664082
0    LinearRegression  0.273990  0.663078
1               Ridge  0.274041  0.663054
4       BayesianRidge  0.275368  0.662448

In [23]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=200,max_depth=15,random_state=42,n_jobs=-1)

model.fit(x_train_final,y_train)

y_pred = model.predict(x_test_final)

r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f"Random Foreste Regressor R2-Score:{r2} and RMSE:{rmse}")

Random Foreste Regressor R2-Score:0.4085714281415187 and RMSE:0.5984725687704453

In [24]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=200,max_depth=50,random_state=42,n_jobs=-1)

model.fit(x_train_final,y_train)

y_pred = model.predict(x_test_final)

r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f"Random Foreste Regressor R2-Score:{r2} and RMSE:{rmse}")

Random Foreste Regressor R2-Score:0.4164750853647742 and RMSE:0.5944602233247543

In [36]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=145,max_depth=50,random_state=42,n_jobs=-1)

model.fit(x_train_final,y_train)

y_pred = model.predict(x_test_final)

r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print(f"Random Foreste Regressor R2-Score:{r2} and RMSE:{rmse}")

Random Foreste Regressor R2-Score:0.4216356063413761 and RMSE:0.5918257710125432

## RandomForestRegressor best prediction with 
                    (n_estimators=145,
                    max_depth=50,
                    random_state=42,
                    n_jobs=-1)