In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
raw_data = pd.read_csv("car_price_prediction.csv")
raw_data.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [3]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  str
 3   Manufacturer      19237 non-null  str
 4   Model             19237 non-null  str
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  str
 7   Leather interior  19237 non-null  str
 8   Fuel type         19237 non-null  str
 9   Engine volume     19237 non-null  str
 10  Mileage           19237 non-null  str
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  str
 13  Drive wheels      19237 non-null  str
 14  Doors             19237 non-null  str
 15  Wheel             19237 non-null  str
 16  Color             19237 non-null  str
 17  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), str(13)
memory usage: 2.6 MB

In [4]:
raw_data.describe()

                 ID         Price    Prod. year     Cylinders       Airbags
count  1.923700e+04  1.923700e+04  19237.000000  19237.000000  19237.000000
mean   4.557654e+07  1.855593e+04   2010.912824      4.582991      6.582627
std    9.365914e+05  1.905813e+05      5.668673      1.199933      4.320168
min    2.074688e+07  1.000000e+00   1939.000000      1.000000      0.000000
25%    4.569837e+07  5.331000e+03   2009.000000      4.000000      4.000000
50%    4.577231e+07  1.317200e+04   2012.000000      4.000000      6.000000
75%    4.580204e+07  2.207500e+04   2015.000000      4.000000     12.000000
max    4.581665e+07  2.630750e+07   2020.000000     16.000000     16.000000

In [5]:
px.histogram(raw_data,x="Prod. year",y="Price")

In [10]:
px.histogram(raw_data,x="Cylinders",y="Price")

In [11]:
px.histogram(raw_data,x="Airbags",y="Price")

In [14]:
x = raw_data.drop(columns=["ID","Price"])
y = raw_data["Price"]

In [15]:
print(x.isnull().sum())
print(y.isnull().sum())

Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64
0

In [16]:
num_cols = x.select_dtypes(include=["int64","float64"]).columns
cat_cols = x.select_dtypes(include=["object"]).columns
print(num_cols)
print(cat_cols)

Index(['Prod. year', 'Cylinders', 'Airbags'], dtype='str')
Index(['Levy', 'Manufacturer', 'Model', 'Category', 'Leather interior',
       'Fuel type', 'Engine volume', 'Mileage', 'Gear box type',
       'Drive wheels', 'Doors', 'Wheel', 'Color'],
      dtype='str')

C:\Users\nigam\AppData\Local\Temp\ipykernel_20344\1792138198.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = x.select_dtypes(include=["object"]).columns

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(13465, 16)
(5772, 16)
(13465,)
(5772,)

In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

scaler = StandardScaler()
x_train_num = scaler.fit_transform(x_train[num_cols])
x_test_num = scaler.transform(x_test[num_cols])

encoder = OneHotEncoder(handle_unknown="ignore",sparse_output=False)
x_train_cat = encoder.fit_transform(x_train[cat_cols])
x_test_cat = encoder.transform(x_test[cat_cols])

x_train_final = np.hstack([x_train_num,x_train_cat])
x_test_final = np.hstack([x_test_num,x_test_cat])
print(x_train_final)

[[ 0.1852177   2.84551131 -1.5148809  ...  0.          0.
   0.        ]
 [ 0.1852177  -0.48519759  1.25559658 ...  0.          0.
   0.        ]
 [ 0.36118301 -0.48519759 -0.59138841 ...  0.          1.
   0.        ]
 ...
 [ 0.53714833  1.18015686 -1.5148809  ...  0.          1.
   0.        ]
 [-1.04653948  1.18015686  1.25559658 ...  0.          1.
   0.        ]
 [-2.8061926  -0.48519759 -0.59138841 ...  0.          0.
   0.        ]]

In [22]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(x_train_final, y_train)

print("R2:", model.score(x_test_final, y_test))

R2: 0.6520119100266004

In [23]:
import joblib

joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoder, "encoder.pkl")

['encoder.pkl']