In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

%matplotlib inline

In [2]:
inputs = pd.read_csv("delhi_traffic_features.csv")
target = pd.read_csv("delhi_traffic_target.csv")
print(inputs.head())
print(target.head())

      Trip_ID       start_area       end_area  distance_km   time_of_day  \
0  TRIP_00001      Vasant Kunj        Kalkaji         9.44         Night
1  TRIP_00002  Greater Kailash        Kalkaji         2.15         Night
2  TRIP_00003        Janakpuri     Model Town        14.54  Morning Peak
3  TRIP_00004     Punjabi Bagh         Dwarka        11.86         Night
4  TRIP_00005           Rohini  Chandni Chowk        20.26     Afternoon

  day_of_week weather_condition traffic_density_level   road_type  \
0     Weekday             Clear                   Low   Main Road
1     Weekend             Clear                   Low   Main Road
2     Weekday              Rain                  High  Inner Road
3     Weekday             Clear                   Low     Highway
4     Weekday               Fog                Medium     Highway

   average_speed_kmph
0                37.8
1                42.7
2                 9.7
3                68.5
4                30.3
      Trip_ID  travel_time_minutes
0  TRIP_00001                 15.3
1  TRIP_00002                  3.0
2  TRIP_00003                 92.7
3  TRIP_00004                 10.6
4  TRIP_00005                 42.0

In [3]:
inputs = inputs.drop("Trip_ID",axis=1)
target = target.drop("Trip_ID",axis=1)
print(inputs.head())
print(target.head())

        start_area       end_area  distance_km   time_of_day day_of_week  \
0      Vasant Kunj        Kalkaji         9.44         Night     Weekday
1  Greater Kailash        Kalkaji         2.15         Night     Weekend
2        Janakpuri     Model Town        14.54  Morning Peak     Weekday
3     Punjabi Bagh         Dwarka        11.86         Night     Weekday
4           Rohini  Chandni Chowk        20.26     Afternoon     Weekday

  weather_condition traffic_density_level   road_type  average_speed_kmph
0             Clear                   Low   Main Road                37.8
1             Clear                   Low   Main Road                42.7
2              Rain                  High  Inner Road                 9.7
3             Clear                   Low     Highway                68.5
4               Fog                Medium     Highway                30.3
   travel_time_minutes
0                 15.3
1                  3.0
2                 92.7
3                 10.6
4                 42.0

In [4]:
numerical_cols = inputs.select_dtypes(include=np.number).columns.tolist()
catagorical_cols = inputs.select_dtypes('object').columns.tolist()
numerical_cols

C:\Users\nigam\AppData\Local\Temp\ipykernel_10976\1872768783.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  catagorical_cols = inputs.select_dtypes('object').columns.tolist()

['distance_km', 'average_speed_kmph']

In [5]:
numerical_data = inputs[numerical_cols]
catagorical_data = inputs[catagorical_cols]
numerical_data.head()

   distance_km  average_speed_kmph
0         9.44                37.8
1         2.15                42.7
2        14.54                 9.7
3        11.86                68.5
4        20.26                30.3

In [6]:
numerical_data.describe()

       distance_km  average_speed_kmph
count  4000.000000         4000.000000
mean     13.342965           28.085300
std       6.367559           17.057224
min       1.510000            4.800000
25%       8.660000           14.500000
50%      13.170000           24.200000
75%      17.230000           38.200000
max      33.010000           93.300000

In [7]:
catagorical_data.nunique()

start_area               25
end_area                 25
time_of_day               4
day_of_week               2
weather_condition         4
traffic_density_level     4
road_type                 3
dtype: int64

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(numerical_data)

MinMaxScaler()

In [9]:
inputs[numerical_cols] = scaler.transform(inputs[numerical_cols])
inputs

,start_area,end_area,distance_km,time_of_day,day_of_week,weather_condition,traffic_density_level,road_type,average_speed_kmph
0,Vasant Kunj,Kalkaji,0.251746,Night,Weekday,Clear,Low,Main Road,0.372881
1,Greater Kailash,Kalkaji,0.020317,Night,Weekend,Clear,Low,Main Road,0.428249
2,Janakpuri,Model Town,0.413651,Morning Peak,Weekday,Rain,High,Inner Road,0.055367
3,Punjabi Bagh,Dwarka,0.328571,Night,Weekday,Clear,Low,Highway,0.719774
4,Rohini,Chandni Chowk,0.595238,Afternoon,Weekday,Fog,Medium,Highway,0.288136
...,...,...,...,...,...,...,...,...,...
3995,Rajouri Garden,Dwarka,0.258095,Morning Peak,Weekday,Clear,Very High,Inner Road,0.032768
3996,Rohini,Dwarka,0.508571,Morning Peak,Weekend,Clear,High,Main Road,0.270056
3997,Preet Vihar,Lajpat Nagar,0.256190,Morning Peak,Weekend,Clear,High,Main Road,0.160452
3998,Karol Bagh,Hauz Khas,0.315238,Evening Peak,Weekend,Heatwave,High,Main Road,0.230508
3999,IGI Airport,Civil Lines,0.537143,Night,Weekday,Fog,Low,Inner Road,0.146893

In [11]:
categorical_cols = inputs.select_dtypes(include=["object", "category"]).columns.tolist()
print(categorical_cols)
print(type(categorical_cols))
print(categorical_cols)

['start_area', 'end_area', 'time_of_day', 'day_of_week', 'weather_condition', 'traffic_density_level', 'road_type']
<class 'list'>
['start_area', 'end_area', 'time_of_day', 'day_of_week', 'weather_condition', 'traffic_density_level', 'road_type']

C:\Users\nigam\AppData\Local\Temp\ipykernel_10976\2146052496.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = inputs.select_dtypes(include=["object", "category"]).columns.tolist()

In [12]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

categorical_cols = inputs.select_dtypes(
    include=["object", "category"]
).columns.tolist()

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

encoder.fit(inputs[categorical_cols])

encoder_cols = encoder.get_feature_names_out(categorical_cols)

encoded = encoder.transform(inputs[categorical_cols])

inputs[encoder_cols] = pd.DataFrame(
    encoded,
    columns=encoder_cols,
    index=inputs.index
)

inputs.drop(columns=categorical_cols, inplace=True)

C:\Users\nigam\AppData\Local\Temp\ipykernel_10976\2553270243.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = inputs.select_dtypes(

In [13]:
from sklearn.model_selection import train_test_split

train_input , test_input,train_target,test_target = train_test_split(inputs,target,test_size=0.3)
print(f"train_input:{train_input.shape}")
print(f"train_target:{train_target.shape}")
print(f"test_input:{test_input.shape}")
print(f"test_target:{test_target.shape}")

train_input:(2800, 69)
train_target:(2800, 1)
test_input:(1200, 69)
test_target:(1200, 1)

In [14]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(train_input,train_target)

LinearRegression()

In [15]:
model.coef_

array([[ 1.01825635e+02, -2.04758411e+01, -1.67951266e+00,
         2.05791255e+00,  5.12466844e-01,  2.24312049e+00,
        -5.81356601e-01, -9.54513819e-01, -8.63423974e-02,
         1.84111684e+00, -1.34806949e-01, -1.25331597e+00,
         1.37829523e+00,  1.34840760e+00,  1.45765908e+00,
         1.24539550e+00,  1.72964307e+00, -1.38797517e+00,
        -4.12792077e-01,  1.00069131e+00, -2.64616955e-01,
         1.49496628e-01,  2.29532019e+00, -6.19363845e+00,
        -1.64348486e+00, -1.27823647e+00, -1.38893295e+00,
        -4.60650331e-01, -3.66404064e-01,  1.34599704e+00,
         3.71173393e+00, -2.16927953e+00, -2.80410473e+00,
         8.44359480e-01,  1.19503203e-01, -7.60669842e-01,
        -3.12198688e+00, -8.43437931e-01, -1.42880931e-01,
         4.34791775e-02,  1.60012350e+00,  3.13121566e-01,
        -1.15567259e+00, -8.53412995e-01, -1.29515312e+00,
         9.16681835e-01,  1.63953049e+00,  2.20810359e+00,
        -2.60395070e+00,  4.80773006e-01,  1.91728589e+00,
         1.43691093e+00, -2.64107845e-01,  4.52997093e-01,
         2.79430402e-02, -2.16832288e-01, -2.44300068e-01,
         2.44300068e-01, -9.24276926e+00,  1.32782260e+01,
        -7.85421178e+00,  3.81875509e+00, -1.95497566e+00,
        -1.56219164e+01, -1.15492273e+01,  2.91261193e+01,
        -1.54481113e+01,  1.49524855e+01,  4.95625808e-01]])

In [16]:
pred = model.predict(test_input)
pred

array([[33.03741669],
       [19.18759456],
       [26.09672469],
       ...,
       [68.48448581],
       [45.36119241],
       [26.44657   ]], shape=(1200, 1))

In [17]:
from sklearn.metrics import root_mean_squared_error,mean_absolute_error,r2_score
print(f"RMSE:{root_mean_squared_error(test_target,pred)}")
print(f"MAE:{mean_absolute_error(test_target,pred)}")
print(f"R2:{r2_score(test_target,pred)}")

RMSE:15.265920202908775
MAE:10.475554070246874
R2:0.7837337067482447

In [20]:
from sklearn.linear_model import (
    LinearRegression,Ridge,Lasso,ElasticNet,
    BayesianRidge,ARDRegression,SGDRegressor,
    PassiveAggressiveRegressor,HuberRegressor,
    RANSACRegressor,TheilSenRegressor
)

models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "ElasticNet": ElasticNet(),
    "BayesianRidge": BayesianRidge(),
    "ARDRegression": ARDRegression(),
    "SGDRegressor": SGDRegressor(max_iter=1000),
    "PassiveAggressive": PassiveAggressiveRegressor(max_iter=1000),
    "Huber": HuberRegressor(),
    "RANSAC": RANSACRegressor(),
    "TheilSen": TheilSenRegressor()
}

results = []

for name,model in models.items():
    try:
        model.fit(train_input,train_target)
        target_pred = model.predict(test_input)
        
        r2 = r2_score(test_target,target_pred)
        rmse = root_mean_squared_error(test_target,target_pred)
        
        results.append((name,r2,rmse))
    except Exception as e:
        print(f"{name} failed :{e}") 

results_df = pd.DataFrame(results,columns=["Model","R2-Score","RMSE"])
results_df = results_df.sort_values(by="RMSE",ascending=False)

print(results_df)

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\deprecation.py:71: FutureWarning: Class PassiveAggressiveRegressor is deprecated; this is deprecated in version 1.8 and will be removed in 1.10. Use `SGDRegressor(loss='epsilon_insensitive', penalty=None, learning_rate='pa1', eta0 = 1.0)` instead.
  warnings.warn(msg, category=FutureWarning)
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

                Model  R2-Score       RMSE
3          ElasticNet  0.255342  28.327413
9              RANSAC  0.405669  25.307114
2               Lasso  0.672402  18.788814
8               Huber  0.747560  16.493310
7   PassiveAggressive  0.766495  15.862686
10           TheilSen  0.783162  15.286068
6        SGDRegressor  0.783165  15.285993
4       BayesianRidge  0.783497  15.274282
1               Ridge  0.783513  15.273723
0    LinearRegression  0.783734  15.265920
5       ARDRegression  0.785009  15.220832

In [24]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=200,
                              random_state=42,
                              max_depth=50,
                              n_jobs=-1)

model.fit(train_input,train_target)
target_pred = model.predict(test_input)

r2 = r2_score(test_target,target_pred)
rmse = root_mean_squared_error(test_target,target_pred)

print(f"Random Forest Regressor r2-Score : {r2} and RMSE : {rmse}")

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Random Forest Regressor r2-Score : 0.9850906586646571 and RMSE : 4.00827766224057

In [25]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=500,
                              random_state=42,
                              max_depth=50,
                              n_jobs=-1)

model.fit(train_input,train_target)
target_pred = model.predict(test_input)

r2 = r2_score(test_target,target_pred)
rmse = root_mean_squared_error(test_target,target_pred)

print(f"Random Forest Regressor r2-Score : {r2} and RMSE : {rmse}")

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Random Forest Regressor r2-Score : 0.9842771037250185 and RMSE : 4.116184607787166

In [35]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=160,
                              random_state=42,
                              max_depth=50,
                              n_jobs=-1)

model.fit(train_input,train_target)
target_pred = model.predict(test_input)

r2 = r2_score(test_target,target_pred)
rmse = root_mean_squared_error(test_target,target_pred)

print(f"Random Forest Regressor r2-Score : {r2} and RMSE : {rmse}")

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Random Forest Regressor r2-Score : 0.9852702384331855 and RMSE : 3.984065117019216

## Random Forest Regressor performs Best with 
                            (n_estimators=160,
                              random_state=42,
                              max_depth=50,
                              n_jobs=-1)