In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv("../data/weatherAUS.csv")
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  str
 1   Location       145460 non-null  str
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  str
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  str
 10  WindDir3pm     141232 non-null  str
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  str
 22  RainTomorrow   142193 non-null  str
dtypes: float64(16), str(7)
memory usage: 25.5 MB

In [11]:
data.dropna(subset=["RainToday","RainTomorrow"],inplace=True)
data.info()

<class 'pandas.DataFrame'>
Index: 140787 entries, 0 to 145458
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           140787 non-null  str
 1   Location       140787 non-null  str
 2   MinTemp        140319 non-null  float64
 3   MaxTemp        140480 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81093 non-null   float64
 6   Sunshine       73982 non-null   float64
 7   WindGustDir    131624 non-null  str
 8   WindGustSpeed  131682 non-null  float64
 9   WindDir9am     131127 non-null  str
 10  WindDir3pm     137117 non-null  str
 11  WindSpeed9am   139732 non-null  float64
 12  WindSpeed3pm   138256 non-null  float64
 13  Humidity9am    139270 non-null  float64
 14  Humidity3pm    137286 non-null  float64
 15  Pressure9am    127044 non-null  float64
 16  Pressure3pm    127018 non-null  float64
 17  Cloud9am       88162 non-null   float64
 18  Cloud3pm       84693 non-null   float64
 19  Temp9am        140131 non-null  float64
 20  Temp3pm        138163 non-null  float64
 21  RainToday      140787 non-null  str
 22  RainTomorrow   140787 non-null  str
dtypes: float64(16), str(7)
memory usage: 25.8 MB

In [14]:
data["RainToday"] = data["RainToday"].map({"Yes":1,"No":0})
data["RainTomorrow"] = data["RainTomorrow"].map({"Yes":1,"No":0})

In [15]:
x = data.drop(columns=["Date","RainTomorrow"])
y = data["RainTomorrow"]
print(x)
print(y)

       Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0        Albury     13.4     22.9       0.6          NaN       NaN
1        Albury      7.4     25.1       0.0          NaN       NaN
2        Albury     12.9     25.7       0.0          NaN       NaN
3        Albury      9.2     28.0       0.0          NaN       NaN
4        Albury     17.5     32.3       1.0          NaN       NaN
...         ...      ...      ...       ...          ...       ...
145454    Uluru      3.5     21.8       0.0          NaN       NaN
145455    Uluru      2.8     23.4       0.0          NaN       NaN
145456    Uluru      3.6     25.3       0.0          NaN       NaN
145457    Uluru      5.4     26.9       0.0          NaN       NaN
145458    Uluru      7.8     27.0       0.0          NaN       NaN

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  WindSpeed3pm  \
0                W           44.0          W        WNW  ...          24.0
1              WNW           44.0        NNW        WSW  ...          22.0
2              WSW           46.0          W        WSW  ...          26.0
3               NE           24.0         SE          E  ...           9.0
4                W           41.0        ENE         NW  ...          20.0
...            ...            ...        ...        ...  ...           ...
145454           E           31.0        ESE          E  ...          13.0
145455           E           31.0         SE        ENE  ...          11.0
145456         NNW           22.0         SE          N  ...           9.0
145457           N           37.0         SE        WNW  ...           9.0
145458          SE           28.0        SSE          N  ...           7.0

        Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  \
0              71.0         22.0       1007.7       1007.1       8.0
1              44.0         25.0       1010.6       1007.8       NaN
2              38.0         30.0       1007.6       1008.7       NaN
3              45.0         16.0       1017.6       1012.8       NaN
4              82.0         33.0       1010.8       1006.0       7.0
...             ...          ...          ...          ...       ...
145454         59.0         27.0       1024.7       1021.2       NaN
145455         51.0         24.0       1024.6       1020.3       NaN
145456         56.0         21.0       1023.5       1019.1       NaN
145457         53.0         24.0       1021.0       1016.8       NaN
145458         51.0         24.0       1019.4       1016.5       3.0

        Cloud3pm  Temp9am  Temp3pm  RainToday
0            NaN     16.9     21.8        NaN
1            NaN     17.2     24.3        NaN
2            2.0     21.0     23.2        NaN
3            NaN     18.1     26.5        NaN
4            8.0     17.8     29.7        NaN
...          ...      ...      ...        ...
145454       NaN      9.4     20.9        NaN
145455       NaN     10.1     22.4        NaN
145456       NaN     10.9     24.5        NaN
145457       NaN     12.5     26.1        NaN
145458       2.0     15.1     26.0        NaN

[140787 rows x 21 columns]
0         0
1         0
2         0
3         0
4         0
         ..
145454    0
145455    0
145456    0
145457    0
145458    0
Name: RainTomorrow, Length: 140787, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(112629, 21)
(28158, 21)
(112629,)
(28158,)

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

num_features = x.select_dtypes(include=["float64"]).columns
cat_features = x.select_dtypes(include=["object"]).columns

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_features),
    ("cat", cat_pipeline, cat_features)
])

C:\Users\nigam\AppData\Local\Temp\ipykernel_1412\1359050908.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = x.select_dtypes(include=["object"]).columns

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC

models = {
    "LogisticRegression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(
        n_estimators=200,
        max_depth=50,
        n_jobs=-1,
        class_weight="balanced"
    ),
    "GradientBoosting": GradientBoostingClassifier(n_estimators=200),
    "SVM": SVC(class_weight="balanced")
}

In [19]:
from sklearn.metrics import accuracy_score,f1_score,classification_report

results = []

try:
    for name, model in models.items():
        pipe = Pipeline([
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipe.fit(x_train, y_train)
        pred = pipe.predict(x_test)

        f1 = f1_score(y_test, pred)
        accuracy_score(y_test,pred)

        print(f"\n{name}")
        print(classification_report(y_test, pred))

        results.append({
            "Model": name,
            "F1-Score": f1
        })
except Exception as e:
    print(f"{name} failed as {e}")
    
pd.DataFrame(results)

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

LogisticRegression
              precision    recall  f1-score   support

           0       0.93      0.80      0.86     21897
           1       0.53      0.78      0.63      6261

    accuracy                           0.80     28158
   macro avg       0.73      0.79      0.74     28158
weighted avg       0.84      0.80      0.81     28158

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

RandomForest
              precision    recall  f1-score   support

           0       0.87      0.96      0.91     21897
           1       0.78      0.49      0.60      6261

    accuracy                           0.86     28158
   macro avg       0.82      0.72      0.76     28158
weighted avg       0.85      0.86      0.84     28158

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

GradientBoosting
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     21897
           1       0.75      0.51      0.60      6261

    accuracy                           0.85     28158
   macro avg       0.81      0.73      0.76     28158
weighted avg       0.84      0.85      0.84     28158

c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\nigam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['RainToday']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

SVM
              precision    recall  f1-score   support

           0       0.94      0.83      0.88     21897
           1       0.58      0.80      0.67      6261

    accuracy                           0.83     28158
   macro avg       0.76      0.82      0.78     28158
weighted avg       0.86      0.83      0.83     28158

                Model  F1-Score
0  LogisticRegression  0.629295
1        RandomForest  0.599096
2    GradientBoosting  0.603953
3                 SVM  0.671565

## SVC(class_weight="balanced") preformes batter than other with